//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDC.UI.SoapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapServiceReference.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/Search", ReplyAction="http://tempuri.org/IPersonService/SearchResponse")]
        int Search(string email, NDC.Common.ViewModels.SearchModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/Search", ReplyAction="http://tempuri.org/IPersonService/SearchResponse")]
        System.Threading.Tasks.Task<int> SearchAsync(string email, NDC.Common.ViewModels.SearchModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : NDC.UI.SoapServiceReference.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<NDC.UI.SoapServiceReference.IPersonService>, NDC.UI.SoapServiceReference.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Search(string email, NDC.Common.ViewModels.SearchModel model) {
            return base.Channel.Search(email, model);
        }
        
        public System.Threading.Tasks.Task<int> SearchAsync(string email, NDC.Common.ViewModels.SearchModel model) {
            return base.Channel.SearchAsync(email, model);
        }
    }
}
